config/routes.rb
BrewReport::Application.routes.draw do
  get "import_archive/list"
  get "icinga_importer/new"
  get "icinga_importer/create"

  post 'icinga_importer/create', to:'icinga_importer#create'
  devise_for :users
  resources :customer_configurations

  resources :sla_per_months

  resources :customers

  resources :downtimes
  devise_scope :user do
    root to: "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
  end

end

app/models/downtime.rb
class Downtime < ActiveRecord::Base
  belongs_to :sla_per_day
  validates :sla_per_day_id, presence: true
  def difference
    #Downtime Length in Minutes
    Rails.logger.debug "Starttime: #{self.start}, Endtime: #{self.end}, Comment was: #{self.comment}"
    (self.end - self.start)
  end

  def self.retrieve_all_by_day(sla_per_day_id)
    self.where('sla_per_day_id = ?', sla_per_day_id).to_a
  end

  def self.check_if_downtime_exists(start_datetime, end_datetime, sla_per_day_id)
    begin
      self.where('start = ? AND end = ? AND sla_per_day_id = ?', start_datetime, end_datetime, sla_per_day_id).take!
    rescue
      return nil
    end
  end
end

app/controllers/downtimes_controller.rb
class DowntimesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_downtime, only: [:show, :edit, :update, :destroy]

  # GET /downtimes
  # GET /downtimes.json
  TITLE = 'Downtimes'

  def index
    @title = TITLE
    @downtime_active = 'active'
    @downtimes = Downtime.includes(sla_per_day:[{sla_per_month:[:customer]}]).to_a
  end

  # GET /downtimes/1
  # GET /downtimes/1.json
  def show
  end

  # GET /downtimes/new
  def new
    @downtime = Downtime.new
  end

  # GET /downtimes/1/edit
  def edit
  end

  # POST /downtimes
  # POST /downtimes.json
  def create
    @downtime = Downtime.new(downtime_params)

    respond_to do |format|
      if @downtime.save
        format.html { redirect_to @downtime, notice: 'Downtime was successfully created.' }
        format.json { render action: 'show', status: :created, location: @downtime }
      else
        format.html { render action: 'new' }
        format.json { render json: @downtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /downtimes/1
  # PATCH/PUT /downtimes/1.json
  def update
    respond_to do |format|
      if @downtime.update(downtime_params)
        format.html { redirect_to @downtime, notice: 'Downtime was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @downtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /downtimes/1
  # DELETE /downtimes/1.json
  def destroy
    @downtime.destroy
    respond_to do |format|
      format.html { redirect_to downtimes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_downtime
      @title = TITLE
      @downtime_active = 'active'
      @downtime = Downtime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def downtime_params
      params.require(:downtime).permit(:start, :downtime_type, :end, :comment, :SLAPerMonth_id)
    end
end

app/helpers/downtimes_helper.rb
module DowntimesHelper
end

app/views/downtimes/_form.html.erb
<%= form_for(@downtime) do |f| %>
  <% if @downtime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@downtime.errors.count, "error") %> prohibited this downtime from being saved:</h2>

      <ul>
      <% @downtime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :downtime_type %><br>
    <%= f.text_field :downtime_type %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :sla_per_day_id %><br>
    <%= f.number_field :sla_per_day_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/downtimes/edit.html.erb
<h1>Editing downtime</h1>

<%= render 'form' %>

<%= link_to 'Show', @downtime %> |
<%= link_to_function 'Back', "history.back()", class: 'button' %>

app/views/downtimes/index.html.erb
<h1>Listing downtimes</h1>

<table class="data_view">
  <thead>
    <tr>
      <th>Start</th>
      <th>Downtimetype</th>
      <th>End</th>
      <th>Comment</th>
      <th>Month</th>
      <th>year</th>
      <th>Customer</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @downtimes.each do |downtime| %>
      <tr>
        <td><%= downtime.start%></td>
        <td><%= downtime.downtime_type %></td>
        <td><%= downtime.end %></td>
        <td><%= downtime.comment %></td>
        <td><%= downtime.sla_per_day.sla_per_month.month %></td>
        <td><%= downtime.sla_per_day.sla_per_month.year %></td>
        <td><%= downtime.sla_per_day.sla_per_month.customer.name %></td>
        <td><%= link_to 'Show', downtime %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'New Downtime', new_downtime_path, class: 'button' %>

app/views/downtimes/new.html.erb
<h1>New downtime</h1>

<%= render 'form' %>

<%= link_to_function 'Back', "history.back()", class: 'button' %>

app/views/downtimes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Showing configuration for Downtime </h1>
<dl class="show_container">

  <dt><strong>Start:</strong></dt>
  <dd><%= @downtime.start %></dd>
  <dt><strong>End:</strong></dt>
  <dd>  <%= @downtime.end %></dd>
  <dt><strong>Downtime type:</strong></dt>
  <dd>  <%=@downtime.downtime_type %></dd>
  <dt><strong>Comment:</strong></dt>
  <dd>    <%= @downtime.comment %></dd>

</dl>
<%= link_to 'Edit', edit_downtime_path(@downtime), class: 'button' %>
<%= link_to_function 'Back', "history.back()", class: 'button' %>
<%= link_to 'Destroy', @downtime, :method => :delete, data: { confirm: 'Are you sure?' }, class:'button' %>