config/routes.rb
BrewReport::Application.routes.draw do
  get "import_archive/list"
  get "icinga_importer/new"
  get "icinga_importer/create"

  post 'icinga_importer/create', to:'icinga_importer#create'
  devise_for :users
  resources :customer_configurations

  resources :sla_per_months

  resources :customers

  resources :downtimes
  devise_scope :user do
    root to: "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
  end

end

app/models/sla_per_month.rb
class SlaPerMonth < ActiveRecord::Base
  belongs_to :customer
  has_many :sla_per_days
  validates :customer, presence: true
  def self.retrieve_all_by_customer(customer)
    self.where('customer_id = ?', customer).to_a
  end

  def self.retrieve_by_month_and_year(month, year, customer_id)
    self.where('month = ? AND year = ? AND customer_id = ?', month, year, customer_id).take
  end

end

app/controllers/sla_per_months_controller.rb
class SlaPerMonthsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sla_per_month, only: [:show, :edit, :update, :destroy]

  # GET /sla_per_months
  # GET /sla_per_months.json
  TITLE = 'Monthly Reports'

  def index
    @title = TITLE
    @sla_per_months = SlaPerMonth.all
  end

  # GET /sla_per_months/1
  # GET /sla_per_months/1.json
  def show
    sla_calculator = UnplannedDowntimeCalculator.new(@sla_per_month.customer)
    @downtime_info = sla_calculator.populate_monthly_sla_for(@sla_per_month)
    @critical_downtimes = sla_calculator.get_all_critical_downtimes_for(@sla_per_month)
  end

  # GET /sla_per_months/new
  def new
    @sla_per_month = SlaPerMonth.new
  end

  # GET /sla_per_months/1/edit
  def edit
  end

  # POST /sla_per_months
  # POST /sla_per_months.json
  def create
    @sla_per_month = SlaPerMonth.new(sla_per_month_params)

    respond_to do |format|
      if @sla_per_month.save
        format.html { redirect_to @sla_per_month, notice: 'Sla per month was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sla_per_month }
      else
        format.html { render action: 'new' }
        format.json { render json: @sla_per_month.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sla_per_months/1
  # PATCH/PUT /sla_per_months/1.json
  def update
    respond_to do |format|
      if @sla_per_month.update(sla_per_month_params)
        format.html { redirect_to @sla_per_month, notice: 'Sla per month was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sla_per_month.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sla_per_months/1
  # DELETE /sla_per_months/1.json
  def destroy
    @sla_per_month.destroy
    respond_to do |format|
      format.html { redirect_to sla_per_months_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sla_per_month
      @title = TITLE
      @sla_per_month = SlaPerMonth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sla_per_month_params
      params.require(:sla_per_month).permit(:month, :year, :customer_id)
    end
end

app/helpers/sla_per_months_helper.rb
module SlaPerMonthsHelper


end

app/views/sla_per_months/_form.html.erb
<%= form_for(@sla_per_month) do |f| %>
  <% if @sla_per_month.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sla_per_month.errors.count, "error") %> prohibited this sla_per_month from being saved:</h2>

      <ul>
      <% @sla_per_month.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sla_per_months/edit.html.erb
<h1>Editing sla_per_month</h1>

<%= render 'form' %>

<%= link_to 'Show', @sla_per_month %> |
<%= link_to 'Back', sla_per_months_path %>

app/views/sla_per_months/index.html.erb
<h1>Listing sla_per_months</h1>

<table class="data_view">
  <thead>
    <tr>
      <th>Month</th>
      <th>Year</th>
      <th>Customer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sla_per_months.each do |sla_per_month| %>
      <tr>
        <td><%= sla_per_month.month %></td>
        <td><%= sla_per_month.year %></td>
        <td><%= sla_per_month.customer.name %></td>
        <td><%= link_to 'Show', sla_per_month %></td>
        <td><%= link_to 'Edit', edit_sla_per_month_path(sla_per_month) %></td>
        <td><%= link_to 'Destroy', sla_per_month, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'New Sla per month', new_sla_per_month_path, class: 'button' %>

app/views/sla_per_months/new.html.erb
<h1>New sla_per_month</h1>

<%= render 'form' %>

<%= link_to 'Back', sla_per_months_path %>

app/views/sla_per_months/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Showing Monthly Report</h1>
<dl class="show_container">

  <dt><strong>Month:</strong></dt>
  <dd><%= @sla_per_month.month %></dd>
  <dt><strong>Year:</strong></dt>
  <dd>  <%= @sla_per_month.year %></dd>
  <dt><strong>Customer:</strong></dt>
  <dd>  <%= @sla_per_month.customer.name %></dd>
  <dt><strong>Unplanned Downtime in seconds:</strong></dt>
  <dd>    <%= @downtime_info.downtime_in_seconds %></dd>
  <dt><strong>General Availability in Seconds</strong></dt>
  <dd>    <%= @downtime_info.configured_availability %></dd>
  <dt><strong>SLA Percentage:</strong></dt>
  <dd>    <%= @downtime_info.get_availability_in_percent %></dd>
  <dt><strong>Downtimes:</strong></dt>
  <dd>
    <dl class="reportList">
      <% @critical_downtimes.each do |critical| %>
      <dt><%= link_to 'Ciritical Downtime:', critical %></dt>
          <dd>From: <%= critical.start %></dd>
          <dd>To:   <%= critical.end %></dd>
          <dd>Comment: <%= critical.comment %></dd>
          <dd>Duration: <%= critical.difference %></dd>
      <% end %>
    </dl>







  </dd>
</dl>
<%= link_to 'Edit', edit_sla_per_month_path(@sla_per_month), class: 'button' %>
<%= link_to 'Back', sla_per_months_path, class: 'button' %>