config/routes.rb
BrewReport::Application.routes.draw do
  get "import_archive/list"
  get "icinga_importer/new"
  get "icinga_importer/create"

  post 'icinga_importer/create', to:'icinga_importer#create'
  devise_for :users
  resources :customer_configurations

  resources :sla_per_months

  resources :customers

  resources :downtimes
  devise_scope :user do
    root to: "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
  end

end

app/models/customer_configuration.rb
class CustomerConfiguration < ActiveRecord::Base
  belongs_to :customer
  validates :customer_id, presence: true
  def get_availablility_in_seconds
    (self.dailySlaEnd - self.dailySlaStart)
  end
end

app/controllers/customer_configurations_controller.rb
class CustomerConfigurationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer_configuration, only: [:show, :edit, :update, :destroy]

  # GET /customer_configurations
  # GET /customer_configurations.json
  TITLE = 'Customer Configuration'

  def index
    @title = TITLE
    @customer_config_active = 'active'
    @customer_configurations = CustomerConfiguration.all
  end

  # GET /customer_configurations/1
  # GET /customer_configurations/1.json
  def show
  end

  # GET /customer_configurations/new
  def new
    @customer_configuration = CustomerConfiguration.new
  end

  # GET /customer_configurations/1/edit
  def edit
  end

  # POST /customer_configurations
  # POST /customer_configurations.json
  def create
    @customer_configuration = CustomerConfiguration.new(customer_configuration_params)

    respond_to do |format|
      if @customer_configuration.save
        format.html { redirect_to @customer_configuration, notice: 'Customer configuration was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer_configuration }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_configurations/1
  # PATCH/PUT /customer_configurations/1.json
  def update
    respond_to do |format|
      if @customer_configuration.update(customer_configuration_params)
        format.html { redirect_to @customer_configuration, notice: 'Customer configuration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_configurations/1
  # DELETE /customer_configurations/1.json
  def destroy
    @customer_configuration.destroy
    respond_to do |format|
      format.html { redirect_to customer_configurations_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_customer_configuration
    @customer_config_active = 'active'
    @title = TITLE
    @customer_configuration = CustomerConfiguration.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_configuration_params
    params.require(:customer_configuration).permit(:customer_id, :dailySlaStart, :dailySlaEnd, :weeklySlaDays, :excludedDays)
  end
end

app/helpers/customer_configurations_helper.rb
module CustomerConfigurationsHelper
end

app/views/customer_configurations/_form.html.erb
<div id="customer_configuration">
<%= form_for(@customer_configuration) do |f| %>
    <% if @customer_configuration.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@customer_configuration.errors.count, 'error') %> prohibited this customer_configuration
            from being saved:</h2>

          <ul>
            <% @customer_configuration.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :customer_id %>
      <br>
      <%= f.collection_select :customer_id, Customer.all, :id, :name %>
    </div>
    <div class="field">
      <%= f.label :dailySlaStart %>
      <br>
      <%= f.time_select :dailySlaStart %>
    </div>
    <div class="field">
      <%= f.label :dailySlaEnd %>
      <br>
      <%= f.time_select :dailySlaEnd %>
    </div>
    <div class="field">
      <%= f.label :weeklySlaDays %>
      <br>

      <div id="checkbox_container">
        <input type="checkbox" class="css-checkbox" value="1" id="mon" name="check"/>
        <label for="mon" class="css-label">Monday</label>
        <input type="checkbox" class="css-checkbox" value="2" id="tue" name="check"/>
        <label for="tue" class="css-label">Tuesday</label>
        <input type="checkbox" class="css-checkbox" value="3" id="wed" name="check"/>
        <label for="wed" class="css-label">Wednesday</label>
        <input type="checkbox" class="css-checkbox" value="4" id="thu" name="check"/>
        <label for="thu" class="css-label">Thursday</label>
        <input type="checkbox" class="css-checkbox" value="5" id="fri" name="check"/>
        <label for="fri" class="css-label">Friday</label>
        <input type="checkbox" class="css-checkbox" value="6" id="sat" name="check"/>
        <label for="sat" class="css-label">Saturday</label>
        <input type="checkbox" class="css-checkbox" value="0" id="sun" name="check"/>
        <label for="sun" class="css-label">Sunday</label>
      </div>
      <%= f.text_field :weeklySlaDays ,{:id => 'weekly_input', :type => 'hidden'}%>
    </div>
    <div class="field">
      <%= f.label :excludedDays %>
      <br>

      <div id="datepicker"></div>
      <br/>
      <%= f.text_field :excludedDays, {:id => 'altField', :type => 'hidden'} %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>
</div>

app/views/customer_configurations/edit.html.erb
<h1>Editing customer_configuration</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Show', @customer_configuration, class: 'button' %>
<%= link_to_function 'Back', "history.back()", class: 'button' %>

app/views/customer_configurations/index.html.erb
<h1>Customer configurations:</h1>

<table class="data_view">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Dailyslastart</th>
      <th>Dailyslaend</th>
      <th>Weeklysladays</th>
      <th>Excludeddays</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_configurations.each do |customer_configuration| %>
      <tr>
        <td><%= customer_configuration.customer.name %></td>
        <td><%= customer_configuration.dailySlaStart.strftime('%H:%M:%S') %></td>
        <td><%= customer_configuration.dailySlaEnd.strftime('%H:%M:%S') %></td>
        <td><%= customer_configuration.weeklySlaDays %></td>
        <td><%= customer_configuration.excludedDays %></td>
        <td><%= link_to 'Show', customer_configuration %></td>
        <td><%= link_to 'Edit', edit_customer_configuration_path(customer_configuration) %></td>
        <td><%= link_to 'Destroy', customer_configuration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'New Customer configuration', new_customer_configuration_path, class: 'button' %>

app/views/customer_configurations/new.html.erb
<h1>New customer_configuration</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_configurations_path, class: 'button' %>

app/views/customer_configurations/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing configuration for <%= @customer_configuration.customer.name %></h1>
<dl class="show_container">

  <dt><strong>Customer:</strong></dt>
  <dd><%= link_to @customer_configuration.customer.name, @customer_configuration.customer %></dd>
  <dt><strong>Dailyslastart:</strong></dt>
  <dd>  <%= @customer_configuration.dailySlaStart.strftime('%H:%M:%S') %></dd>
  <dt><strong>Dailyslaend:</strong></dt>
  <dd>  <%= @customer_configuration.dailySlaEnd.strftime('%H:%M:%S') %></dd>
  <dt><strong>Weeklysladays:</strong></dt>
  <dd>    <%= @customer_configuration.weeklySlaDays %></dd>
  <dt><strong>Excludeddays:</strong></dt>
  <dd>  <%= @customer_configuration.excludedDays %></dd>

</dl>

<%= link_to 'Edit', edit_customer_configuration_path(@customer_configuration), class: 'button' %>
<%= link_to_function 'Back', "history.back()", class: 'button' %>