config/routes.rb
BrewReport::Application.routes.draw do
  get "import_archive/list"
  get "icinga_importer/new"
  get "icinga_importer/create"

  post 'icinga_importer/create', to:'icinga_importer#create'
  devise_for :users
  resources :customer_configurations

  resources :sla_per_months

  resources :customers

  resources :downtimes
  devise_scope :user do
    root to: "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrewReport</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="no-sidebar">

<!-- Header Wrapper -->

<div id="header-wrapper" class="wrapper">
  <div class="container">
    <div class="row">
      <div class="12u">

        <!-- Header -->
        <div id="header">

          <!-- Logo -->
          <div id="logo">
            <h1><a href="#">BrewReport</a></h1>
          </div>
          <!-- /Logo -->
              <!-- Nav -->
              <nav id="nav">
                <ul>
                  <li><%= link_to 'Customer', customers_path %></li>
                  <li><%= link_to 'Configuration', customer_configurations_path %></li>
                  <li><%= link_to 'Monthly reports', sla_per_months_path %></li>
                  <li><%= link_to 'Downtimes', downtimes_path %></li>
                  <li><%= link_to 'HTTP Importer', icinga_importer_new_path %></li>
                  <li><%= link_to 'Logout', '/sign_out' %></li>
                </ul>
              </nav>
              <!-- /Nav -->
        </div>
        <!-- /Header -->

      </div>
    </div>
  </div>
</div>

<!-- /Header Wrapper -->
<% Time.zone = 'Berlin' %>

<!-- Main Wrapper -->
<div class="wrapper wrapper-style2">
  <div class="title"><%= @title %></div>
  <div class="container">
    <div class="row">
      <div class="12u">

        <!-- Main -->
        <div id="main">
          <div>
            <div class="row">
              <div class="12u skel-cell-important">

                <!-- Content -->
                <div id="content">
                  <article class="is is-post">

                    <%= yield %>

                  </article>

                </div>
                <!-- /Content -->

              </div>
            </div>
          </div>
        </div>
        <!-- /Main -->

      </div>
    </div>
  </div>
</div>
<!-- /Main Wrapper -->

<!-- Highlights Wrapper -->

<!-- /Highlights Wrapper -->

<!-- Footer Wrapper -->
<div id="footer-wrapper" class="wrapper">
  <div class="title">The Rest Of It</div>
  <div class="container">
    <div class="row">
      <div class="12u">

        <!-- Footer -->
        <div id="footer">
          <hr/>
          <div>
            <div class="row">
              <div class="6u">

                <!-- Contacts -->
                <section class="footer-two">
                  <div class="feature-list feature-list-small">
                    <div>
                      <div class="row">
                        <div class="6u">
                          <section>
                            <h3 class="fa fa-home">Mailing Address</h3>

                            <p>
                              Musterfirma<br/>
                              Musterstr. 7<br/>
                              12345 Musterort
                            </p>
                          </section>
                        </div>
                        <div class="6u">
                          <section>
                            <h3 class="fa fa-comment">Social</h3>

                            <p>
                              <a href="#">something</a><br/>
                              <a href="#">facebook.com/untitled</a><br/>
                            </p>
                          </section>
                        </div>
                      </div>
                      <div class="row">
                        <div class="6u">
                          <section>
                            <h3 class="fa fa-envelope">Email</h3>

                            <p>
                              <a href="#">info@untitled.tld</a>
                            </p>
                          </section>
                        </div>
                        <div class="6u">
                          <section>
                            <h3 class="fa fa-phone">Phone</h3>

                            <p>
                              (000) 555-0000
                            </p>
                          </section>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
                <!-- /Contacts -->

              </div>
            </div>
          </div>
          <hr/>
        </div>
        <!-- /Footer -->

        <!-- Copyright -->
        <div id="copyright">
									<span>
										&copy; Untitled. Design by <a href="http://html5up.net/">HTML5 UP</a>.
									</span>
        </div>
        <!-- /Copyright -->

      </div>
    </div>
  </div>
</div>
<!-- /Footer Wrapper -->

</body>
</html>